openapi: 3.0.3
info:
  title: API de Encurtador de URL
  version: 1.0.0
  description: API simples para encurtar URLs e redirecionar a URL encurtada

servers:
  - url: http://localhost:8080
    description: Servidor local

paths:
  /shorten:
    post:
      summary: Encurta uma URL
      description: Recebe uma URL longa e devolve uma URL encurtada
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  format: uri
                  example: "https://www.exemplo.com/artigo/muito-longo"
      responses:
        '201':
          description: URL encurtada criada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  shortUrl:
                    type: string
                    example: "http://localhost:8080/abc123"

  /{shortCode}:
    get:
      summary: Redireciona para a URL original
      description: Recebe o código curto da URL e redireciona para a URL original
      parameters:
        - name: shortCode
          in: path
          required: true
          description: Código da URL encurtada
          schema:
            type: string
            example: "abc123"
      responses:
        '302':
          description: Redirecionamento para a URL original
          headers:
            Location:
              description: URL de destino do redirecionamento
              schema:
                type: string
                example: "https://www.exemplo.com/artigo/muito-longo"
        '404':
          description: Código de URL não encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "URL não encontrada"