// Code generated by MockGen. DO NOT EDIT.
// Source: hashid.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIDHasher is a mock of IDHasher interface.
type MockIDHasher struct {
	ctrl     *gomock.Controller
	recorder *MockIDHasherMockRecorder
}

// MockIDHasherMockRecorder is the mock recorder for MockIDHasher.
type MockIDHasherMockRecorder struct {
	mock *MockIDHasher
}

// NewMockIDHasher creates a new mock instance.
func NewMockIDHasher(ctrl *gomock.Controller) *MockIDHasher {
	mock := &MockIDHasher{ctrl: ctrl}
	mock.recorder = &MockIDHasherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDHasher) EXPECT() *MockIDHasherMockRecorder {
	return m.recorder
}

// DecodeUrl mocks base method.
func (m *MockIDHasher) DecodeUrl(shortUrl string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecodeUrl", shortUrl)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecodeUrl indicates an expected call of DecodeUrl.
func (mr *MockIDHasherMockRecorder) DecodeUrl(shortUrl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecodeUrl", reflect.TypeOf((*MockIDHasher)(nil).DecodeUrl), shortUrl)
}

// EncodeUrl mocks base method.
func (m *MockIDHasher) EncodeUrl(id int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncodeUrl", id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EncodeUrl indicates an expected call of EncodeUrl.
func (mr *MockIDHasherMockRecorder) EncodeUrl(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncodeUrl", reflect.TypeOf((*MockIDHasher)(nil).EncodeUrl), id)
}
